# Spring Data Source 설정 
spring:

    output:
        ansi:
            enabled: always 

    # Thymeleaf (1. 루트폴더 변경, 2. 타임리프 캐시 설정 변경)
    thymeleaf:
        prefix: classpath:templates/ # templates 라는 폴더안에 thymeleaf view 파일이 있다.
        check-template-location: true
        suffix: .html
        mode: HTML
        cache: false